version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Zig dependencies (when package manager is stable)
  - package-ecosystem: "other"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "zig"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore patch updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
